issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - typecheck
    - linters:
        - lll
      source: "^//go:generate "